version: 2.1

orbs:
  slack: circleci/slack@4.1.1

executors:
  app:
    docker:
      - image: circleci/node:14.15.0
    working_directory: ~/repo
  slack:
    docker:
      - image: 'cibuilds/base:latest'
    resource_class: small

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo $CIRCLE_BRANCH
  - &restore-cache
    restore_cache:
      keys:
        - app-{{ checksum "package.json"}}
        - app-
  - &install-dependencies
    run:
      name: Install dependencies
      command: npm install
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{ checksum "package.json"}}
  - &install-aws-cli
    run:
      name: Installing AWS CLI
      working_directory: /
      command: |
        sudo apt-get install python-dev python-pip
        sudo pip install awscli
  - &build-project
    run:
      name: Build project
      command: |
        npm install
        npm run build
        zip build.zip -r build
        echo "Build successful"
  - &run-linter
    run:
      name: Run linter
      command: |
        npm run lint
  - &run-prettier
    run:
      name: Run Prettier
      command: |
        npm run prettier:check

jobs:
  build:
    executor: app
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *install-dependencies
      - *save-cache

  lint:
    executor: app
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *run-linter

  check-code-style:
    executor: app
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *run-prettier

  deploy-to-aws-s3:
    executor: app
    steps:
      - checkout
      - *show-current-branch-name
      - *install-aws-cli
      - *build-project
      - run:
          name: Deploy to AWS S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              aws --region $AWS_REGION s3 sync ~/repo/build s3://${AWS_BUCKET_PROD} --delete
            elif [ "${CIRCLE_BRANCH}" == "staging" ]
            then 
              aws --region $AWS_REGION s3 sync ~/repo/build s3://${AWS_BUCKET_STAGING} --delete
            else
              aws --region $AWS_REGION s3 sync ~/repo/build s3://${AWS_BUCKET_DEV} --delete
            fi

  deploy-to-aws-cloudfront:
    executor: app
    steps:
      - checkout
      - *show-current-branch-name
      - *install-aws-cli
      - *build-project
      - run:
          name: Activate cloudfront
          command: |
            aws configure set preview.cloudfront true
            aws configure set preview.create-invalidation true
      - run:
          name: Deploy to AWS S3
          command: |
            if ["$CIRCLE_BRANCH" == "master"]
            then
              aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_PROD --paths "/*"
            elif ["$CIRCLE_BRANCH" == "staging"]
            then
              aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_STAGING --paths "/*"
            else
              aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_DEV --paths "/*" 
            fi

  notify-via-slack:
    executor: slack
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Deployment successful! :tada:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "On the $CIRCLE_BRANCH branch"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View branch",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://app.circleci.com/pipelines/github/HarryMumford",
                    "action_id": "button-action"
                  }
                }
              ]
            }
          event: pass
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Deployment failed! :disappointed:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "On the $CIRCLE_BRANCH branch"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View branch",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://app.circleci.com/pipelines/github/HarryMumford",
                    "action_id": "button-action"
                  }
                }
              ]
            }
          event: fail
workflows:
  build_and_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - check-code-style:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - deploy-to-aws-s3:
          requires:
            - check-code-style
            - lint
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - deploy-to-aws-cloudfront:
          requires:
            - deploy-to-aws-s3
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - notify-via-slack:
          context: slack-secrets
          requires:
            - deploy-to-aws-cloudfront
          filters:
            branches:
              only:
                - develop
                - staging
                - master
